[bot]
owner_tg_id = 123456789
token = "6300572797:AAG42WIKf42Z8cSkAm75lLuNzwILQkbpb1o"
drop_pending = true
use_webhook = false
use_class_middlewares = true
actions_timeout = 0.2
page_size = 10

logger.name = "BotLogger"
logger.level = "DEBUG"
logger.stream = "stdout"
logger.file_path = "logs/bot.log"
logger.format = "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

# allowed_updates = [...] or "ALL"

state_storage.type = "memory"
state_storage.redis.host = "localhost"
state_storage.redis.port = 6379
# state_storage.redis.db = 0
state_storage.redis.password = "password"
# state_storage.redis.prefix = "prefix"

# webhook.base_url = "webhook_base_url"
# webhook.path = "webhook_path"
# webhook.secret_token = "secret token"
# webhook.cert_path = "cert_path"
# webhook.ip_address = "ip_address"
# webhook.max_connections = 40

# telegram_api_url = "telegram_api_url"

# [extra sections if any]
# ...

[logger]
name = "MyAppLogger"
level = "INFO"
stream = "stdout"
file_path = "logs/myapp.log"
format = "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

[messages]
welcome = "Приветствую! Это бот ША-2023. Именно здесь вы можете зарегистрироваться на квест."  # TODO
help = "Регистрация команды: /reg \n\nРегистрция КПшника: /manager_reg <пароль>\n\nРегистрация Администратора: /admin_reg <пароль>"  # TODO
anti_flood = "Пожалуйста, прекрати, я и с первого раза понял"  # TODO
unknown_update = "Данная функция пока что не согласована командой оргов, все претензии к ним"  # TODO, be creative
rating = "Rating message:\n\n{}"
not_enough_teams = "Недостаточно участников для начала игры"
not_enough_points = "Недостаточно КПшек для начала игры"
starting_point = "Your starting point: {}"
broadcast_failures = "Broadcast failures:\n\n{}"
broadcast_success = "Broadcast success"
game_started = "Game started"
invalid_admin_password = "Invalid admin password"
admin_password_set = "Admin password set"
admin_registered = "Администратор зарегистрирован"
choose_team = "Выберите команду"
get_add_balance_amount = "Enter amount to add"
balance_added = "Balance added"
invalid_manager_password = "Invalid manager password"
manager_password_set = "Manager password set"
manager_registered = "Manager registered"
invalid_point_name = "Invalid point name"
point_registered = "Point registered"
team_balance = "Ваш баланс: {}"
get_teamname = "Напишите название своей команды:"
team_registered = "Вы успешно зарегистрированы!"
invalid_teamname = "Некорректное название, пожалуйста, выберите другое"
teamname_taken = "Название занято, пожалуйста, выберите другое"


[buttons]
help = "Help"
